version: "3.3"

services:
  front:
    image: sermalenk/skypro-front:lesson_37
    ports:
      - '8080:80'
    depends_on:
      - api

  api:
    image: jokerred/todonotes:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:8000
    environment:
      DB_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"

  migrations:
    image: jokerred/todonotes:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python3 manage.py makemigrations &&
            python3 manage.py migrate"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
