# Generated by Django 4.0.3 on 2022-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveBigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('verification_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'TG User',
                'verbose_name_plural': 'TG User',
            },
        ),
    ]
